version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "9342:9342"
    command: sh -c "pip install -r requirements.txt && python app.py"